name: My Second Workflow
on:
  pull_request:
    branches: [main]

jobs:
  builds2:
    # Create VM with Ubuntu OS
    runs-on: ubuntu-20.04

    steps:
    # First step to say hello
    - name: Greeting steps
      run: |
        echo "Hello there"
        
    # Checkout the code
    - name: Checkout my code
      uses: actions/checkout@v4
    
    - name: Print content of repo
      run: |
        ls

    # Install Python
    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Check Python version
      run: |
        python --version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov

    # Run tests with pytest
    - name: Testing with Pytest
      run: |
        pytest

    # Checkout hidden repo
    - name: Checkout Hidden Repo
      uses: actions/checkout@v4
      with:
        repository: XIAO0101-star/uobhidden
        path: hiddenfolder
        token: ${{secrets.SECRETUOB}}

    # Print hidden files
    - name: Print out hidden things
      run: |
        ls
        cd hiddenfolder
        ls
    
        
    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: ${{ github.repository }} has been successfullly deployed.
          
