name: My Second Workflow
on:
  pull_request:
    branches: [main]
    
jobs:
  my-job2:
    name: My Job
    runs-on: ubuntu-20.04
    
    steps:
      # Step 1: Check out the source code from the repository
      - name: Check out code
        uses: actions/checkout@v3
      - name: print content of repo
        run: |
          ls

      # Step 2: Print a greeting message
      - name: Print a greeting
        run: |
          echo "Hello there"

      # Step 3: Set up Python (you can specify the version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' #Set Python version (e.g., '3.9')
      - name: check version of python
        run: |
          python --version

      # Step 4: Install dependencies (if you have a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: begin test
        run: |
          pytest -v -cov -junitxml=report.xml

      - name: checkout hidden Repo
        uses: actions/checkout@v3
        with:
          repository: XIAO0101-star/uobhidden
          path: hiddenfolder
          token: ${{ secrets.SECRETUOB }}

      - name: print out hidden things
        run: |
          ls
          cd hiddenfolder
          ls
